services:
  site:
    network_mode: "host"
    container_name: aurora-docsy
    command: bash -c "npm i . && npm run start"
    image: docker.io/library/node:latest@sha256:e961046fec20896e8904f2b4a8b4c7e5ca91826d84d8d33d83dbaa61f942069e
    working_dir: /srv/docs
    volumes:
      - "./:/srv/docs:Z"
    ports:
      - "3000:3000"
