name: Generate Docs PDF
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  pdf:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 20

      - name: Install Prince
        run: |
          curl -LO https://www.princexml.com/download/prince-16.2-linux-generic-x86_64.tar.gz
          tar zxf prince-16.2-linux-generic-x86_64.tar.gz
          cd prince-16.2-linux-generic-x86_64
          yes "" | sudo ./install.sh
      - name: Build PDF
        run: npx docusaurus-prince-pdf@1.2.1 --toc -u https://docs.getaurora.dev -o pdf/aurora.pdf
      - name: Upload results
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: aurora
          # The output filename can be specified with --output option
          path: pdf/aurora.pdf
          if-no-files-found: error
          overwrite: true
      - name: Upload Release Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload --clobber 0.1 pdf/aurora.pdf
