name: check-spelling

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.fedora_version }}
  cancel-in-progress: true

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Check for typos
        uses: crate-ci/typos@3504f4613b41e223d38c08c6953c3ef30bf29fac # version 1.0.4
        with:
          files: ./README.md ./docs
          config: ./typos.toml
